# Generated by Django 6.0.1 on 2026-01-25 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('MIXTOS', 'Pagos Mixtos')], max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='cajas.caja')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_anulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_venta'], name='ventas_vent_fecha_v_357f1c_idx'), models.Index(fields=['metodo_pago'], name='ventas_vent_metodo__7195f7_idx')],
            },
        ),
    ]
