# Generated by Django 6.0.1 on 2026-02-02 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('xml', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada'), ('PENDIENTE', 'Pendiente')], max_length=20)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='ventas.venta')),
            ],
            options={
                'indexes': [models.Index(fields=['numero'], name='ventas_bole_numero_7381a2_idx'), models.Index(fields=['fecha_emision'], name='ventas_bole_fecha_e_4b918b_idx')],
            },
        ),
    ]
