# Generated by Django 6.0.1 on 2026-01-25 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('CERRAR_VENTA', 'Cerrar Venta'), ('ABRIR_CAJA', 'Abrir Caja'), ('CERRAR_CAJA', 'Cerrar Caja'), ('APERTURAR_MESA', 'Aperturar Mesa'), ('CERRAR_MESA', 'Cerrar Mesa')], max_length=20)),
                ('modulo', models.CharField(choices=[('VENTAS', 'Ventas'), ('INVENTARIO', 'Inventario'), ('CAJAS', 'Cajas'), ('PEDIDOS', 'Pedidos'), ('PRODUCTOS', 'Productos'), ('USUARIOS', 'Usuarios'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['accion'], name='auditoria_a_accion_a0755b_idx'), models.Index(fields=['modulo'], name='auditoria_a_modulo_9c8d7e_idx'), models.Index(fields=['fecha_creacion'], name='auditoria_a_fecha_c_2deb1b_idx')],
            },
        ),
    ]
