# Generated by Django 6.0.1 on 2026-01-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ANULAR', 'Anular'), ('ELIMINAR', 'Eliminar'), ('ABRIR_VENTA', 'Abrir Venta'), ('CERRAR_VENTA', 'Cerrar Venta'), ('ABRIR_CAJA', 'Abrir Caja'), ('CERRAR_CAJA', 'Cerrar Caja'), ('APERTURAR_MESA', 'Aperturar Mesa'), ('CERRAR_MESA', 'Cerrar Mesa')], max_length=20),
        ),
    ]
