# Generated by Django 6.0.1 on 2026-01-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modulo'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ENCARGADO', 'Encargado'), ('MESERO', 'Mesero'), ('COCINERO', 'Cocinero'), ('BARTENDER', 'Bartender')], default='MESERO', max_length=20),
        ),
    ]
