# Generated by Django 6.0.1 on 2026-01-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('restaurantes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='restaurantes.restaurante'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='tipo_insumo',
            field=models.CharField(choices=[('CRITICO', 'Crítico'), ('GENERAL', 'General'), ('UNITARIO', 'Unitario')], default='GENERAL', help_text='Crítico (carnes, licores), General (verduras, condimentos), Unitario (congelados/porciones)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='ingrediente',
            unique_together={('restaurante', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento'], name='inventario__tipo_mo_89d562_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='inventario__fecha_m_ff429d_idx'),
        ),
    ]
