# Generated by Django 6.0.1 on 2026-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='inventario__tipo_mo_89d562_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientoinventario',
            name='inventario__fecha_m_ff429d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ingrediente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo_insumo',
            field=models.CharField(choices=[('CRITICO', 'Crítico'), ('GENERAL', 'General')], default='GENERAL', help_text='Crítico (carnes, licores), General (verduras, condimentos), Unitario (congelados/porciones)', max_length=20),
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='restaurante',
        ),
    ]
