# Generated by Django 6.0.1 on 2026-01-25 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(choices=[('COMIDA', 'Comida'), ('BEBESTIBLE', 'Bebestible'), ('BEBIDA_ALCOLICA', 'Bebida Alcohólica'), ('INGREDIENTE', 'Ingrediente'), ('INSUMO', 'Insumo')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('favorito', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
