# Generated by Django 6.0.1 on 2026-01-25 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0002_sala_mesa_pos_x_mesa_pos_y_alter_mesa_estado_and_more'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PREPARACION', 'En preparación'), ('SERVIDO', 'Servido'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('camarero', models.ForeignKey(limit_choices_to={'rol': 'MESERO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='mesas.mesa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrasladoMesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('mesa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='mesas.mesa')),
                ('mesa_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='mesas.mesa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
