# Generated by Django 6.0.1 on 2026-01-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='restaurantes.restaurante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('restaurante', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('restaurante', 'nombre')},
        ),
    ]
