# Generated by Django 6.0.1 on 2026-01-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_restaurante_producto_restaurante_and_more'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='restaurantes.restaurante'),
        ),
    ]
