# Generated by Django 6.0.1 on 2026-01-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_sala_mesa_pos_x_mesa_pos_y_alter_mesa_estado_and_more'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('restaurante', 'nombre')},
        ),
    ]
