# Generated by Django 6.0.1 on 2026-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_sala_restaurante_alter_sala_nombre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='sala',
            name='restaurante',
        ),
    ]
