# Generated by Django 6.0.1 on 2026-02-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_caja_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='restaurante',
        ),
    ]
