# Generated by Django 6.0.1 on 2026-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ENCARGADO', 'Encargado'), ('MESERO', 'Mesero'), ('COCINERO', 'Cocinero'), ('COMENSAL', 'Comensal'), ('BARTENDER', 'Bartender')], default='MESERO', max_length=20),
        ),
    ]
